ALTER TABLE commentcodes MODIFY name VARCHAR(32);
ALTER TABLE displaycodes MODIFY name VARCHAR(32);
ALTER TABLE pollanswers MODIFY qid VARCHAR(20) DEFAULT '' NOT NULL, MODIFY answer VARCHAR(255);
ALTER TABLE pollquestions MODIFY qid VARCHAR(20) DEFAULT '' NOT NULL, MODIFY
question VARCHAR(255) DEFAULT '' NOT NULL;
ALTER TABLE pollvoters MODIFY qid VARCHAR(20) DEFAULT '' NOT NULL, MODIFY id
VARCHAR(35) DEFAULT '' NOT NULL;
ALTER TABLE statuscodes MODIFY name VARCHAR(32);
ALTER TABLE topics MODIFY tid VARCHAR(20) DEFAULT '' NOT NULL, MODIFY image
VARCHAR(30), MODIFY alttext VARCHAR(40);
ALTER TABLE vars MODIFY name VARCHAR(32) DEFAULT '' NOT NULL, MODIFY value
VARCHAR(127), MODIFY description VARCHAR(255);
