UPDATE vars SET value=CONCAT(value, ",\ncomment_toggle,\ncomment_remove") WHERE name='perms';
UPDATE perm_groups SET group_perms = CONCAT(group_perms, ',comment_remove,comment_toggle') WHERE perm_group_id = 'Superuser';

INSERT INTO blocks (bid, block, aid, description, category, theme, language) VALUES ('comment_remove_link', ' (<A CLASS="light" HREF="%%rootdir%%/comments/%%sid%%/%%cid%%/remove">suppress comment</A>)', '1', '<P>The link to remove a comment (replace with a placeholder indicating that the comment has been deleted), if the user has the <B>comment_remove</B> perm. Special keys sid and cid identify the comment.</P>', 'Comments', 'default', 'en');
INSERT INTO blocks (bid, block, aid, description, category, theme, language) VALUES ('comment_delete_link', ' (<A CLASS="light" HREF="%%rootdir%%/comments/%%sid%%/%%cid%%/delete">delete</A>)', '1', '<P>The link to delete a comment (remove entirely and make replies to this comment become replies to this comment\'s parent), if the user has the <B>comment_delete</B> perm. Special keys sid and cid identify the comment.</P>', 'Comments', 'default', 'en');
INSERT INTO blocks (bid, block, aid, description, category, theme, language) VALUES ('comment_toggle_link', ' (<A CLASS="light" HREF="%%rootdir%%/comments/%%sid%%/%%cid%%/%%toggle%%">toggle</A>)', '1', '<P>The link to toggle a comment between topical and editorial, if the user has the <B>comment_toggle</B> perm. Special keys sid and cid identify the comment, and toggle sets the type (topical or editorial).</P>', 'Comments', 'default', 'en');
INSERT INTO blocks (bid, block, aid, description, category, theme, language) VALUES ('removed_comment_body', '<P><EM>This comment has been deleted by %%nick%%</EM></P>', '1', '<P>The body of a removed comment. One special key, nick, contains the nickname of the admin who removed the comment. If you have jokers on your site who may claim that their comments have been wiped, I recommend putting something in this block that users can normally not put in their comments, as an "authenticity" marker.</P>', 'Comments', 'default', 'en');
INSERT INTO blocks (bid, block, aid, description, category, theme, language) VALUES ('removed_comment_subject', '(Comment Deleted)', '1', '<P>The subject of a removed comment. One special key, nick, contains the nickname of the admin who removed the comment.</P>', 'Comments', 'default', 'en');

